cs50/django/airline/airline/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("flights/", include("flights.urls"))
]

cs50/django/airline/flights/urls.py
from django.urls import path, include
from . import views

app_name = "flights"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:flight_id>", views.flight, name="flight"),
    path("<int:flight_id>/book", views.book, name="book")
]

cs50/django/airline/flights/models.py
from django.db import models

# Create your models here.

class Airport(models.Model):
    code = models.CharField(max_length=3)
    city = models.CharField(max_length=64)

    def __str__(self):
        return f"{self.city} ({self.code})"




class Flights(models.Model):
    # origin = models.CharField(max_length=64)
    # destination = models.CharField(max_length=64)


    # models.CASCADE means if we delete an airport from Airport
    # table then the entries which points to that airport in Flights
    # table will also be deleted 
    origin = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name="departures")
    destination = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name="arrivals")
    duration = models.IntegerField()

    def __str__(self):
        return f"{self.id}: {self.origin} to {self.destination}"

class Passenger(models.Model):
    firstName = models.CharField(max_length=64)
    lastName = models.CharField(max_length=64)
    flights = models.ManyToManyField(Flights, blank=True, related_name="passengers")


    def __str__(self) -> str:
        return f"{self.firstName} {self.lastName}"

cs50/django/airline/flights/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse

from .models import Flights, Passenger

# Create your views here.
def index(request):
    return render(request, "flights/index.html", {
        "flights": Flights.objects.all()
    })

def flight(request, flight_id):
    flight = Flights.objects.get(pk=flight_id)

    return render(request, "flights/flights.html", {
        "flight": flight,
        "passengers": flight.passengers.all(),
        "non_passenger": Passenger.objects.exclude(flights=flight).all()

    })

def book(request, flight_id):
    if request.method == "POST":
        flight = Flights.objects.get(pk=flight_id)
        passenger = Passenger.objects.get(pk=int(request.POST["passenger"]))
        passenger.flights.add(flight)
        return HttpResponseRedirect(reverse("flights:flight", args=(flight.id,)))
    

cs50/django/airline/flights/templates/flights/flights.html
{% extends "flights/layout.html" %}

{% block body %}
    <h1>Flight {{ flight.id }}</h1>

    <ul>
        <li>Origin: {{ flight.origin }}</li>
        <li>Destination: {{ flight.destination }}</li>
        <li>Duration: {{ flight.duration }}</li>
    </ul>

    <h2>Passengers</h2>

    <ul>
        {% for passenger in passengers %}
            <li>{{ passenger }}</li>
        {% empty %}
            <li>No Passengers.</li>
        {% endfor %}
    </ul>

    <h2>Add Passenger</h2>

    <form action="{% url 'flights:book' flight.id %}" method="post">
        {% csrf_token %}
        <select name="passenger">
            {% for passenger in non_passenger %}
                <option value="{{ passenger.id }}">{{ passenger }}</option>
            {% endfor %}

        </select>
        <input type="submit">
    </form>

    <a href="{% url 'flights:index' %}">Back to Flight List</a>

{% endblock %}

cs50/django/airline/flights/templates/flights/index.html
{% extends "flights/layout.html" %}

{% block body %}
    <h1>Flights</h1>
    <ul>
        {% for flight in flights %}
            <a href="{% url 'flights:flight' flight.id %}">
                <li>Flight {{flight.id}}: {{flight.origin}} to {{flight.destination}}</li>
            </a>    

        {% endfor %}
    </ul>


{% endblock %}

cs50/django/airline/flights/templates/flights/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flights</title>
</head>
<body>
    {% block body %}
    {% endblock %}
    
</body>
</html>